spring:
    profiles:
        active:
        - develop
---
# local dev profile
spring:
  config:
    activate:
      on-profile:
      - develop
  #console colors
  output:
    ansi:
      enabled: always

  datasource: 
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#logging levels
debug: true
logging:
  level:
    root: error
    org:
      springframework:
        web: debug
mainTitle:
  title: Tour of local develop
server:
  port: 8082
  

